---
- name: "Use a template to describe the region data set naming conventions"
  
  gather_facts: false
  hosts: all
  environment: "{{ environment_vars }}"

  module_defaults:
    group/ibm.ibm_zos_cics.region:
      cics_data_sets:
        sdfhload: CTS610.CICS740.SDFHLOAD
      region_data_sets:
        template: "STEWF.RGNS.DEMO.<< data_set_name >>"

  tasks:
    - name: "Allocate and initialize a CSD"
      ibm.ibm_zos_cics.csd:
        state: initial
      
    - name: Create a group list for my region, and add the auto install terminal definitions to it
      ibm.ibm_zos_cics.csd:
        state: changed
        input_location: INLINE
        input_content: |
          ADD GROUP(DFHTERMC) LIST(DFHLIST1)

          LIST LIST(DFHLIST1) OBJECTS

    - name: Provision a local catalog
      ibm.ibm_zos_cics.global_catalog:
        state: initial